import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  box1: {
    flex: 1.2,
    alignItems: 'center',
  },
  box2: {
    flex: 1,
  },
  box3: {
    flex: 1,
  },
  callBox: {
    flex: 1,
    alignItems: 'center',
    width: '100%',
  },
  text: {
    marginTop: '3%',
    color: '#fff',
    fontSize: 18,
    fontWeight: '500',
  },
  textava: {
    marginTop: '2.5%',
    color: '#000000',
    fontSize: 18,
    fontWeight: 'bold',
  },
  textend: {
    marginTop: '2.5%',
    color: '#0096FF',
    fontSize: 14,
    fontWeight: 'normal',
  },
  textavaincall: {
    marginTop: '2.5%',
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  call: {
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  iconBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: '3%',
  },
  settingBox: {
    alignItems: 'flex-end',
    flex: 1.5,
    justifyContent: 'center',
    width: '100%',
    flexDirection: 'row',
    marginBottom: '15%',
  },
  homeBox: {
    alignSelf: 'center',
    flex: 1,
    justifyContent: 'center',
    marginBottom: '10%',
  },
  button: {
    marginHorizontal: '16%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#a9a9a9',
    borderColor: '#fff',
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  usersListContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  floatRight: {
    height: 56,
    width: 56,
    borderRadius: 28,
    borderColor: '#fff',
    backgroundColor: '#a9a9a9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  homebtn: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#a9a9a9',
    borderColor: '#fff',
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  endcallbtn: {
    backgroundColor: '#ffffff',
  },
  speaker: {
    height: 36,
    width: 36,
  },
  ava: {
    height: 128,
    width: 128,
    borderRadius: 64,
    borderColor: '#6ac5fe',
    borderWidth: 1,
  },
  Icon: {
    height: 24,
    width: 24,
    margin: '1.5%',
  },
  pick: {
    color: '#ffffff',
    textAlign: 'left',
    justifyContent: 'center',
    alignContent: 'flex-start',
    width: '75%',
    margin: '2%',
    paddingLeft: '4%',
  },
  counterbox: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    margin: '2%',
    marginTop: '5%',
    width: '50%',
  },
  border: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: '#fff',
    width: 64,
    height: 64,
    borderRadius: 32,
  },
});
