import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  // input: {
  //   textAlign: 'center',
  //   marginTop: '2%',
  //   borderColor: '#fff',
  //   borderWidth: 1,
  //   width: '95%',
  //   borderRadius: 20,
  //   paddingHorizontal: 10,
  //   paddingVertical: 15,
  //   color: '#fff',
  // },
  box1: {
    flex: 1.2,
    alignItems: 'center',
  },
  box2: {
    flex: 1,
  },
  callBox: {
    flex: 1,
    alignItems: 'center',
    width: '100%',
  },
  text: {
    marginTop: '2.5%',
    color: '#fff',
    fontSize: 18,
    fontWeight: '500',
  },
  textava: {
    marginTop: '2.5%',
    color: '#000000',
    fontSize: 18,
    fontWeight: 'bold',
  },
  call: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  settingBox: {
    alignItems: 'flex-end',
    flex: 1.5,
    justifyContent: 'space-between',
    width: '100%',
    flexDirection: 'row',
    marginBottom: '10%',
  },
  button: {
    marginHorizontal: '10%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#a9a9a9',
    borderColor: '#fff',
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  usersListContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  floatRight: {
    height: 64,
    width: 64,
    borderRadius: 32,
    borderColor: '#fff',
    backgroundColor: '#a9a9a9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  speaker: {
    height: 40,
    width: 40,
  },
  ava: {
    height: 128,
    width: 128,
    borderRadius: 64,
    borderColor: '#6ac5fe',
    borderWidth: 1,
  },
  Icon: {
    height: 24,
    width: 24,
    margin: '1.5%',
  },
  pick: {
    color: '#ffffff',
    textAlign: 'left',
    justifyContent: 'center',
    alignContent: 'flex-start',
    width: '75%',
    margin: '2%',
    paddingLeft: '4%',
  },
  counterbox: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    margin: '1%',
    width: '60%',
  },
});
